name: Scheduled Workflow

on:
  schedule:
    - cron: "* * * * *"   # every day at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running nightly job at midnight"
